version: "3"

services:
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: api
      MONGO_INITDB_ROOT_PASSWORD: api

  api:
    image: ghcr.io/kunalsin9h/api:latest
    depends_on:
      - mongodb
    ports:
      - "9999:9999"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      HOST: 0.0.0.0
      PORT: 9999
