version: "3"

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    deploy:
      mode: global
    environment:
      MONGO_INITDB_ROOT_USERNAME: api
      MONGO_INITDB_ROOT_PASSWORD: api
    volumes:
      - ./db_data:/data/db

  api:
    image: ghcr.io/kunalsin9h/api:latest
    depends_on:
      - mongo
    ports:
      - "9999:9999"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      HOST: 0.0.0.0
      PORT: 9999
      DB_TIMEOUT: 4000
      MEILI_HOST: http://meili:7700
      MEILI_MASTER_KEY:  16-BYTES-MASTER-KEY
      MONGODB_URL: mongodb://api:api@mongo:27017

  meili:
    image: ghcr.io/kunalsin9h/meilisearch:latest
    ports:
      - "7700:7700"
    deploy:
      mode: global
    environment:
      MEILI_MASTER_KEY: 16-BYTES-MASTER-KEY    
    volumes:
      - ./data.ms:/meilisearch/data.ms

