name: API CD

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    name: "Build the docker image"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: build
        run: |
          docker build -t ghcr.io/kunalsin9h/api:latest .
      - name: push
        if: github.ref == 'refs/heads/master'
        run: |
          echo "${{ secrets.GHCR }}" | docker login ghcr.io -u "kunalsin9h" --password-stdin
          docker push ghcr.io/kunalsin9h/api:latest

  lint:
    name: "Linting"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21"
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59.1
